### ISSUE TITLE
my offering of help

### ISSUE THREAD

**Issue by AndraesBoni** [ZRiddle/PokeAlertsOnboarding#26]
I am not a programmer or a coder at all, but I am a mapper.  I took all your individual area maps and plotted them together. ![current](https://cloud.githubusercontent.com/assets/21106871/17780081/434d8d7c-6527-11e6-9342-ff3454b62d84.PNG) Crowdsourcing the mapping wasn't a bad idea to start, but with the large amount of new area requests coming in there's going to be more and more issues.  

I would love to help out refining the boundaries of the current areas and laying out new areas to fit  nicely together with the existing.  (I'm also completely new to this whole github thing, so feel free to guide me a bit...)  Obviously I don't know what exact info your code needs, but I can make changes to the polygons easily in arcmap and then export vertices or coordinates or whatever is best.  Contact me here, or on reddit /u/andraes.  I hope I can help out, the only thing I ask for in return is that you prioritize saratoga springs and eagle mountain ;-)

**Comment by roboticsplits** [comment]
I really hope he takes you up on your offer!

If the boundaries get redone, I'd recommend #ut-lehi-traverse & #ut-lehi-1200w3200n be split by the freeway. So much of #ut-lehi-traverse is Thanksgiving Point Golf Course Gastly nest...and because you'd need to cross the freeway, you wouldn't have time to get to it (ideally that nest would be on one channel anyways).

Obviously the diagonal freeway doesn't work with rectangles, but if the boundaries could be a triangle that would be ideal.
